language: python
python:
- '3.6'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam package --template-file highscore-service/template.yaml --s3-bucket highscore-service --output-template-file highscore-service/packaged.yaml
- build.sh
deploy:
  - provider: script
    script: sam deploy --template-file highscore-service/packaged.yaml --capabilities CAPABILITY_IAM --stack-name travis-serverless-test
    skip_cleanup: true
    on:
      branch: master
#   notifications:
#     email:
#       on_failure: always
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "tetris-frontend"
    skip_cleanup: true
    region: $AWS_DEFAULT_REGION
    local_dir: frontend/react-tetris/build
  
env:
  global:
  - AWS_DEFAULT_REGION=ap-southeast-2
  - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
  - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
