AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  highscore-service

  Sample SAM Template for highscore-service

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  TableName:
    Type: String
    Default: 'highScoreTable'
    Description: The name of the new DynamoDB table to create and save high scores to.
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'

Resources:
  # The Lambda Function
  HighScoreFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: high_score/
      Handler: app.lambda_handler
      Runtime: python3.6
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        UpdateHighScore:
          Type: Api
          Properties:
            Path: /update-hs
            Method: post
            RestApiId: !Ref HighScoreApi
        GetHighScore:
          Type: Api
          Properties:
            Path: /get-hs
            Method: get
            RestApiId: !Ref HighScoreApi

  HighScoreDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  HighScoreApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: High Score AWS Api Gateway
      StageName: Prod
      Cors: "'*'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://highscore-service/swagger.yaml

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HighScoreApi:
    Description: "API Gateway endpoint URL for Production stage for High Score backend service"
    Value: !Sub "https://${HighScoreApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  HighScoreApiRestApiId:
    Description: 'API Gateway ARN for Basic AWS API Gateway'
    Value: !Ref HighScoreApi
    Export:
      Name: HighScoreApi-RestApiId
  HighScoreAPiRootResourceId:
    Value: !GetAtt HighScoreApi.RootResourceId
    Export:
      Name: HighScoreApi-RootResourceId
  HighScoreFunction:
    Description: "High Score Lambda Function ARN"
    Value: !GetAtt HighScoreFunction.Arn
  HighScoreFunctionIamRole:
    Description: "Implicit IAM Role created for High Score function"
    Value: !GetAtt HighScoreFunctionRole.Arn
